name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Packing release
        run: |
          
          echo ${{ github.ref }}
          rm -rf ".github"
          rm -rf ".git"
          rm -f "flyway.conf"
          rm -f "config.php"
          rm -f "config-analytics.php"
          rm -f "config-dist.php"
          rm -f "config-extra.php"
          rm -f "config-unittest.php"
          find -type f -name "*.config" -delete
          
          zip -r portal.zip * 

      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./portal.zip
          asset_name: portal-${{ github.ref }}.zip
          asset_content_type: application/zip